# Generated by Django 4.2.6 on 2024-01-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Management',
            fields=[
                ('exam_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=15)),
                ('exam_date', models.DateTimeField()),
                ('room_id', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Room_Doing',
            fields=[
                ('erd_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='normal', max_length=10)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Abnormal_behavior.exam_management')),
            ],
        ),
        migrations.CreateModel(
            name='User_Management',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('upassword', models.CharField(max_length=20)),
                ('utype', models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP')], default='normal', max_length=10)),
                ('remainday', models.IntegerField()),
                ('ucode', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='History_Management',
            fields=[
                ('his_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('htime', models.DateTimeField()),
                ('erd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Abnormal_behavior.exam_room_doing')),
            ],
        ),
        migrations.AddField(
            model_name='exam_room_doing',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Abnormal_behavior.user_management'),
        ),
        migrations.AddField(
            model_name='exam_management',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Abnormal_behavior.user_management'),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('biil_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('bill_date', models.DateTimeField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Abnormal_behavior.user_management')),
            ],
        ),
    ]
