# Generated by Django 4.1.4 on 2024-01-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abnormal_behavior', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_management',
            name='duration',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history_management',
            name='label',
            field=models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], default='normal', max_length=10),
        ),
    ]
