# Generated by Django 4.1.4 on 2024-01-26 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Abnormal_behavior', '0004_alter_bill_bill_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history_management',
            old_name='label',
            new_name='labels',
        ),
    ]
