# Generated by Django 4.1.4 on 2024-01-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abnormal_behavior', '0005_rename_label_history_management_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_management',
            name='upassword',
            field=models.CharField(max_length=30),
        ),
    ]
