# Generated by Django 4.1.4 on 2024-02-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abnormal_behavior', '0006_alter_user_management_upassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_management',
            name='state',
            field=models.CharField(choices=[('unlock', 'Unlock'), ('lock', 'Lock')], default='unlock', max_length=10),
        ),
    ]
