# Generated by Django 4.1.4 on 2024-02-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abnormal_behavior', '0008_alter_bill_bill_id_alter_exam_management_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_management',
            name='state',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=10),
        ),
    ]
