# Generated by Django 4.1.4 on 2024-02-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abnormal_behavior', '0009_alter_history_management_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_room_doing',
            name='state',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=10),
        ),
    ]
