# Generated by Django 4.2.9 on 2024-02-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abnormal_behavior', '0010_alter_exam_room_doing_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('qmail', models.EmailField(max_length=254)),
                ('qname', models.CharField(max_length=100)),
                ('qphone', models.CharField(max_length=15)),
                ('qadvise', models.CharField(choices=[('Exam', 'Exam'), ('Tool', 'Tool')], max_length=10)),
                ('qmessage', models.TextField()),
            ],
        ),
    ]
