# Generated by Django 4.1.4 on 2024-02-28 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Abnormal_behavior', '0010_alter_exam_room_doing_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP_state',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('IP', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('state', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], default='online', max_length=10)),
                ('erd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Abnormal_behavior.exam_room_doing')),
            ],
        ),
    ]
