# Generated by Django 4.2.9 on 2024-02-27 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Abnormal_behavior', '0011_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('ser_id', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('Exam', 'Exam'), ('Tool', 'Tool')], default='Exam', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User_Services',
            fields=[
                ('user_id', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Abnormal_behavior.services')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Abnormal_behavior.user_management')),
            ],
        ),
        migrations.CreateModel(
            name='Services_Price',
            fields=[
                ('sp_id', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Abnormal_behavior.services')),
            ],
        ),
    ]
