# Generated by Django 4.2.9 on 2024-03-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Abnormal_behavior', '0011_ip_state'),
        ('Abnormal_behavior', '0012_services_user_services_services_price'),
    ]

    operations = [
    ]
